plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id "maven-publish"
}

/* Data Generation */
loom {
    splitEnvironmentSourceSets()
    mods {
        "jineric" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
	accessWidenerPath = file("src/main/resources/jineric.classtweaker")
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

/* Dependencies */
repositories {
	mavenCentral()
	maven {
		url "https://api.modrinth.com/maven"
	}
	maven {
		url = 'https://maven.minecraftforge.net/'
	}
	maven {
		url "https://jitpack.io"
	}
	maven {
		url = "https://maven.shedaniel.me/"
	}
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/releases/"
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

version = project.version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "com.github.glitchfiend:TerraBlender-fabric:${project.minecraft_version}-${project.terrablender_version}"
	api "com.terraformersmc:modmenu:${project.mod_menu_version}"
//	api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {exclude(group: "net.fabricmc.fabric-api")}
//	api "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
	include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${project.mixin_extras_version}")))
	include(implementation("com.terraformersmc:biolith-fabric:${project.biolith_version}"))
	include(implementation ('com.github.Chocohead:Fabric-ASM:v2.3'))
}

/* Resource Processing */
processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

/* Publishing */
java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
	}
}
