org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true

# Mod Properties
mod_name = Jineric Mod
mod_id = jineric
version = b7.1.2+26.1.2
maven_group = jingy.jineric
archives_base_name = jineric

# Fabric Properties
# https://fabricmc.net/develop/
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.152.1+26.1.2

# Dependencies
# https://linkie.shedaniel.dev/
# https://modrinth.com/mod/terrablender/versions
terrablender_version = 26.1.2.0.2
# https://modrinth.com/mod/biolith/versions
biolith_version = 3.6.0-alpha.9
# https://modrinth.com/mod/rei/versions?l=fabric
rei_version = 26.1.819+fabric
# https://modrinth.com/mod/cloth-config/versions?l=fabric
cloth_config_version = 26.1.154+fabric
# https://modrinth.com/mod/modmenu/versions?l=fabric
mod_menu_version = 18.0.0-beta.1
# https://github.com/LlamaLad7/MixinExtras/releases
mixin_extras_version = 0.5.4