org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true

# Mod Properties
mod_name = Jineric Mod
mod_id = jineric
version = b7.1.0+1.21.4
maven_group = jingy.jineric
archives_base_name = jineric

# Fabric Properties
# https://fabricmc.net/develop/
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.12

# Fabric API
fabric_version=0.119.6+1.21.5

# Dependencies
# https://modrinth.com/mod/terrablender/versions
terrablender_version = 5.0.0.0
# https://modrinth.com/mod/biolith/versions
biolith_version = 3.3.0-alpha.4
# https://linkie.shedaniel.dev/
rei_version = 18.0.800
cloth_config_version = 17.0.144
mod_menu_version = 14.0.0-rc.2
mixin_extras_version = 0.5.0-beta.5