package net.jineric.jineric_mod.mixin.client.add;

import net.minecraft.client.renderer.blockentity.state.ChestRenderState;
import org.spongepowered.asm.mixin.Mixin;

@Mixin(ChestRenderState.ChestMaterialType.class)
public enum ChestMaterialTypeMixin {
    JINERIC_WOODEN_SPRUCE,
//    JINERIC_WOODEN_OAK,
    JINERIC_WOODEN_BIRCH,
    JINERIC_WOODEN_JUNGLE,
    JINERIC_WOODEN_ACACIA,
    JINERIC_WOODEN_DARK_OAK,
    JINERIC_WOODEN_MANGROVE,
    JINERIC_WOODEN_CHERRY,
    JINERIC_WOODEN_PALE_OAK,
//    JINERIC_WOODEN_POPLAR,
    JINERIC_WOODEN_BAMBOO,
    JINERIC_WOODEN_CRIMSON,
    JINERIC_WOODEN_WARPED,
    JINERIC_WOODEN_TRAPPED_SPRUCE,
//    JINERIC_WOODEN_TRAPPED_OAK,
    JINERIC_WOODEN_TRAPPED_BIRCH,
    JINERIC_WOODEN_TRAPPED_JUNGLE,
    JINERIC_WOODEN_TRAPPED_ACACIA,
    JINERIC_WOODEN_TRAPPED_DARK_OAK,
    JINERIC_WOODEN_TRAPPED_MANGROVE,
    JINERIC_WOODEN_TRAPPED_CHERRY,
    JINERIC_WOODEN_TRAPPED_PALE_OAK,
//    JINERIC_WOODEN_TRAPPED_POPLAR,
    JINERIC_WOODEN_TRAPPED_BAMBOO,
    JINERIC_WOODEN_TRAPPED_CRIMSON,
    JINERIC_WOODEN_TRAPPED_WARPED,
}
