# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build Jineric
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Common Artifacts
          path: common/build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Fabric Artifacts
          path: fabric/build/libs/